ch0070_battle_in_1=所为虽小，亦当全力以报。
ch0070_lobby_1=不可思议的感觉呢。毕竟我很少离开自己的房间，这里的体验更显特别了。
ch0070_lobby_2=虽然这取决于您，有朝一日，这里也会成为我所熟悉的景色吗。
ch0070_lobby_3=啊，哪怕是成为我的房间也未尝不可。
ch0070_lobby_4=怎么，只是随口一说罢了。
ch0070_lobby_5=…您想怎么理解都可以。毕竟想象是个人的自由。
ch0070_tactic_defeat_2=已是遥不可及了吗……
ch0070_tactic_defeat_1=遭受挫折了吗…
ch0070_battle_in_1=不用担心，我会处理的。
ch0070_growup_4=向您致以感谢，向未来致以赞颂。
ch0070_exweapon_get=您要把这个…送给我？没什么，只是单纯地出乎意料罢了。难办了呢，都不知道该说什么才好。不过…现在的我能够心领这份好意了。
ch0070_eventmission_login_2=啊，我已等您许久了……没什么，也就是和直觉差不多的吧。